######################################
#
# BUSCO summary figure
# @version 3.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2017, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("figures/","1_busco_cDNAcupcake.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#81d0fc", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.9

# Legend
my_title <- "BUSCO cDNAcupcake (collapsed)"

# Font
my_family <- "sans"
my_size_ratio <- 1.2

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Nipponbare', 'Nipponbare', 'Nipponbare', 'Nipponbare', 'N22', 'N22', 'N22', 'N22', 'Dular', 'Dular', 'Dular', 'Dular', 'Anjali', 
                'Anjali', 'Anjali', 'Anjali', 'CT9993', 'CT9993', 'CT9993', 'CT9993', 'M202', 'M202', 'M202', 'M202', 'Moroberekan', 'Moroberekan', 
                'Moroberekan', 'Moroberekan', 'IR62266', 'IR62266', 'IR62266', 'IR62266', 'IR64', 'IR64', 'IR64', 'IR64', 'IR72', 'IR72', 'IR72', 'IR72')
my_species <- factor(my_species)
levels(my_species)
my_species <- factor(my_species,levels(my_species)[rev(c(3, 9, 1, 4, 5, 6, 2, 7, 8, 10))]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(46.5, 18.4, 3.3, 31.8, 47.9, 14.9, 5.1, 32.1, 30.0, 9.5, 6.3, 54.2, 40.5, 7.9, 4.2, 47.4, 49.1, 17.2, 5.6, 28.1, 46.0, 19.8, 3.3, 30.9, 47.2, 16.5, 4.7, 31.6, 43.3, 20.2, 5.1, 31.4, 48.4, 18.1, 2.8, 30.7, 42.1, 13.3, 4.9, 39.7)
my_values <- c(200, 79, 14, 137, 206, 64, 22, 138, 129, 41, 27, 233, 174, 34, 18, 204, 211, 74, 24, 121, 198, 85, 14, 133, 203, 71, 20, 136, 186, 87, 22, 135, 208, 78, 12, 132, 181, 57, 21, 171)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
  labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(expand=c(0,0), limits=c(0,104), labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 
  
  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(1.5)*my_size_ratio, face = "bold")) +
  theme(legend.position="bottom",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank())+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1)) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.3)*my_size_ratio)) + 
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE)) +
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))

for(i in rev(c(1:length(levels(my_species))))){
  detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
  total_buscos <- sum(detailed_values)
  figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
}

  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
